name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # matches your local version

      # 3. Set up Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 4. Install Python dependencies (if any)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 5. Render Quarto site
      - name: Render site
        run: quarto render

      # 6. Optional debug: list files
      - name: List files after render
        run: ls -R

      # 7. Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


